### ISSUE TITLE
Add domain: `.GNO`

### ISSUE THREAD

**Issue by nykma** [NextDotID/relation_server#136]
https://x.com/gnosischain/status/1786104778881392889

https://genomedomains.com

Claims that it has Interoperability with ENS . Need to dig it deeper after it becomes online

**Comment by ZhongFuze** [comment]
https://github.com/NextDotID/relation_server/pull/138

**Comment by ZhongFuze** [comment]
# Fetch and Process GNS Transactions and Genome Domain Data


We have updated the GNS_REGISTRY from 0x4f132A7e39B1D717B39C789eB9EC1e790092042B to 0x5dc881dda4e4a8d312be3544ad13118d1a04cb17. We need to ensure our application correctly fetches and processes GNS-related transactions and domain data. Below are the steps and actions required.

## Additional Information

```
    GNS Registry: 0x5dc881dda4e4a8d312be3544ad13118d1a04cb17
    Public Resolver: 0x6d3b3f99177fb2a5de7f9e928a9bd807bf7b5bad
    ERC1967 Proxy: 0xd7b837a0e388b4c25200983bdaa3ef3a83ca86b7
```


## Tasks
### 1. Fetch All EOAs Interacting with GNS

App Name: gnosis-resolver-tx-fetch
API Endpoint: Gnosis Scan API
API Key: Retrieve API Key

    Details: Use the provided API to fetch all EOAs that have interacted with the GNS registry at 0x5dc881dda4e4a8d312be3544ad13118d1a04cb17.

### 2. Query Reverse Resolved Genome Domain by Address

Repository: lookup_gno
API Endpoint: http://data_process_hostname/lookup/gno/address

    Details: Implement a query to retrieve the genome domain that has reverse resolution set for a given address.

### 3. Query Owned and Resolved Genome Domains by Address

Repository: https://github.com/ZhongFuze/data_process/blob/main/src/service/gnosis_domains.py#L340
https://graphigo.prd.space.id/query

    Details: Implement a query to retrieve all genome domains owned by a given address and those with resolve resolution set.

### 4. Scheduled Task for Data Fetch

    Details: Set up a cron job to run every hour at the 30th minute. This job should fetch new data from the Gnosis registry, handle creates, updates, and perform necessary deletions while respecting the API rate limit.

### 5. RelationService Query API

Service URL: http://data_process_hostname/data_server/genome

    Endpoints:
        Get Name: http://data_process_hostname/data_server/genome/get_name?tld=gno&address=${address}
        Get Address: http://data_process_hostname/data_server/genome/get_address?tld=gno&domain=${domain_name}

### 6. Test Cases

Test the implementation with the following cases:
```
    0xc9af7bbea391364e40fd6ebde0e9911129d94905 -> gnome.gno
    0x6d910bea79aaf318e7170c6fb8318d9c466b2164 -> shiva.gno
    0xfceec24912535a47c0cba436977537ad225a2562 -> genome.gno (also has 85 items like poap.gno)
    0x23b13307372e1cccfc4f0b0e5dc937714604752c -> kevin.gno
    0xc2fb4b3ea53e10c88d193e709a81c4dc7aec902e -> vitalik.gno
    0xca771eda0c70aa7d053ab1b25004559b918fe662 -> None (reverse resolve)
```
